# -*- coding: utf-8 -*-
"""clever_movie.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i41JQyBCOL14N1zJ6RISf8d0jykynnfn

Сначала создаю телеграм - бота:
"""

pip install pyTelegramBotAPI #устанавливаю библиотеку

import telebot
botTimeWeb = telebot.TeleBot('6767214855:AAHGuoOnbmlpC5FRpGq6AY-pkbQJxmFDXSI')#здесь уникальный токен бота
from telebot import types

#обработчик сообщений
@botTimeWeb.message_handler(commands=['start'])
def startBot(message):
  first_mess = f"<b>{message.from_user.first_name} {message.from_user.last_name}</b>, привет!\nХочешь я помогу тебе выбрать фильм для просмотра?"
  #создание кнопки типа inline(отображается под сообщением), переправляет пользователя на следующее сообщение
  markup = types.InlineKeyboardMarkup()
  button_yes = types.InlineKeyboardButton(text = 'Да', callback_data = 'yes')
  markup.add(button_yes)

  botTimeWeb.send_message(message.chat.id, first_mess, parse_mode='html', reply_markup=markup)

#функционал кнопки "Да"
@botTimeWeb.callback_query_handler(func=lambda call:True)
def response(function_call):
  if function_call.message:
     if function_call.data == "yes":
        second_mess = "Напиши мне в ответном сообщении, какое у тебя настроение и чего ты ожидаешь от просмотра))"
        botTimeWeb.send_message(function_call.message.chat.id, second_mess)
        #обработка запроса закончена
        botTimeWeb.answer_callback_query(function_call.id)

#непрерывная работа бота
botTimeWeb.infinity_polling()